---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: scentia-os
description: Scentia OS – Optimized NVIDIA/Bazzite environment with Hyprland tuning and performance enhancements

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:

  ##########################################################
  # SYSTEM FILES + NVIDIA + HYPRLAND ENV
  ##########################################################
  - type: files
    files:
      # System folder copy
      - source: system
        destination: /

      # NVIDIA Persistence Daemon
      - content: |
          [Unit]
          Description=NVIDIA Persistence Daemon
          After=multi-user.target

          [Service]
          Type=forking
          ExecStart=/usr/bin/nvidia-persistenced --verbose
          ExecStop=/usr/bin/killall nvidia-persistenced
          Restart=always

          [Install]
          WantedBy=multi-user.target
        path: /etc/systemd/system/nvidia-persistenced.service

      # NVIDIA Power Service
      - content: |
          [Unit]
          Description=NVIDIA Power Management

          [Service]
          ExecStart=/usr/bin/nvidia-powerd
          Restart=always

          [Install]
          WantedBy=graphical.target
        path: /etc/systemd/system/nvidia-powerd.service

      # Hyprland / NVIDIA Environment Variables
      - content: |
          LIBVA_DRIVER_NAME=nvidia
          __GLX_VENDOR_LIBRARY_NAME=nvidia
          GBM_BACKEND=nvidia-drm
          __GL_GSYNC_ALLOWED=1
          __GL_VRR_ALLOWED=1
          __GL_MaxFramesAllowed=1
        path: /etc/environment

      # NVIDIA Coolbits (Overclock + Fan Control)
      - content: |
          Section "Device"
              Identifier "Nvidia Card"
              Driver "nvidia"
              Option "Coolbits" "28"
              Option "AllowEmptyInitialConfiguration"
          EndSection
        path: /etc/X11/xorg.conf.d/90-nvidia-coolbits.conf

      # LACT Daemon
      - content: |
          [Unit]
          Description=LACT GPU Control
          After=graphical.target

          [Service]
          ExecStart=/usr/bin/lactd
          Restart=always

          [Install]
          WantedBy=graphical.target
        path: /etc/systemd/system/lactd.service

      # LACT Fan Curve
      - content: |
          {
            "version": 1,
            "fan_control": {
              "enabled": true,
              "default_mode": "curve",
              "curve": [
                {"temp": 30, "speed": 25},
                {"temp": 40, "speed": 35},
                {"temp": 50, "speed": 45},
                {"temp": 60, "speed": 60},
                {"temp": 70, "speed": 75},
                {"temp": 80, "speed": 90}
              ]
            }
          }
        path: /etc/lact/config.json

      # LACT Overclock Profiles
      - content: |
          [profile.default]
          core_offset = 0
          mem_offset = 0
          power_limit = "default"

          [profile.oc_safe]
          core_offset = 100
          mem_offset = 300
          power_limit = "max"

          [profile.oc_aggressive]
          core_offset = 160
          mem_offset = 600
          power_limit = "max"
        path: /etc/lact/profiles.toml

      # Desktop Entry Launcher
      - content: |
          [Desktop Entry]
          Type=Application
          Name=LACT GPU Control
          Exec=lact-gui
          Icon=lact
          Categories=System;Settings;
          Terminal=false
        path: /usr/share/applications/lact.desktop

  ##########################################################
  # DNF PACKAGES (Native Heroic, LACT, Dev Tools, NVIDIA)
  ##########################################################
  - type: dnf
    repos:
      copr:
        - atim/starship
        - jakoolits/Hyprland
        - cheat/heroic-games-launcher
        - xnorbr/lact

    install:
      packages:
        # Essentials
        - micro
        - starship
        - git
        - curl
        - aria2
        - tar
        - ffmpeg

        # Development
        - gcc
        - gcc-c++
        - clang
        - llvm
        - cmake
        - ninja-build
        - make

        # Python
        - python3
        - python3-pip
        - python3-virtualenv
        - python3-devel
        - python3-setuptools
        - python3-wheel

        # Wine Gaming Stack
        - wine
        - wine-gecko
        - wine-mono

        # Hyprland
        - hyprland
        - xdg-desktop-portal-hyprland
        - hyprpaper
        - waybar
        - rofi-wayland
        - grim
        - slurp
        - swaylock

        # FUSE / Mesa
        - fuse3
        - fuse3-libs
        - mesa-libEGL
        - mesa-libGL
        - mesa-libGLU

        # CUDA + NVIDIA compute stack
        - cuda
        - cuda-cudart
        - cuda-nvrtc
        - cuda-nvtx
        - libcublas
        - libcublas-devel
        - cudnn8
        - cudnn8-devel

        # Gaming / Vulkan tools
        - gamemode
        - gamemode-devel
        - mangohud
        - mango
        - vkBasalt
        - vulkan-tools
        - vulkan-loader
        - vulkan-headers
        - vulkan-validation-layers

        # Native Heroic build
        - heroic-games-launcher-bin

        # Native LACT
        - lact

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ##########################################################
  # DEFAULT FLATPAKS
  ##########################################################
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  ##########################################################
  # SIGNING MODULE
  ##########################################################
  - type: signing
