---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: scentia-os
description: "Scentia OS – Hyprland (built from source) + LACT + Dev + Gaming + CUDA"
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:

  ##########################################################
  # FILES
  ##########################################################
  - type: files
    files:
      - source: lactd.service
        destination: /etc/systemd/system/lactd.service

      - source: environment
        destination: /etc/environment

      - source: build-hyprland.sh
        destination: /usr/local/bin/build-hyprland.sh

  ##########################################################
  # DNF — v0 schema (NO version: field)
  ##########################################################
  - type: dnf
    repos:
      copr:
        - xnorbr/lact

    install:
      packages:
        - git
        - curl
        - gcc
        - gcc-c++
        - clang
        - llvm
        - make
        - cmake
        - ninja-build
        - meson
        - pkg-config
        - python3
        - python3-pip
        - python3-mako
        - wlroots-devel
        - wayland-devel
        - wayland-protocols-devel
        - libxkbcommon-devel
        - libinput-devel
        - libseat-devel
        - libevdev-devel
        - libudev-devel
        - libdrm-devel
        - libwayland-egl-devel
        - libxkbcommon-x11-devel
        - hyprland
        - waybar
        - rofi-wayland
        - hyprpaper
        - grim
        - slurp
        - swaylock
        - gamemode
        - mangohud
        - mangohud-core
        - vkBasalt
        - vulkan-tools
        - vulkan-validation-layers
        - lact
        - cuda
        - cuda-cudart
        - cuda-nvrtc
        - cuda-nvtx
        - libcublas
        - libcublas-devel
        - cudnn8
        - cudnn8-devel

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ##########################################################
  # SCRIPT — v0 schema uses "scripts" NOT "path"
  ##########################################################
  - type: script
    scripts:
      - /usr/local/bin/build-hyprland.sh

  ##########################################################
  # FLATPAKS — no version field allowed
  ##########################################################
  - type: default-flatpaks
    configurations:
      - scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe

  ##########################################################
  # SIGNING — v0 schema
  ##########################################################
  - type: signing
