---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: Scentia-OS
description: Fully optimized NVIDIA-focused Scentia-OS image with AI tools, gaming enhancements, and system tuning.

base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:

  ##########################################################
  # SYSTEM FILES + NVIDIA + HYPRLAND OPTIMIZATIONS
  ##########################################################
  - type: files
    files:
      - source: system
        destination: /

      # NVIDIA Persistence Daemon
      - content: |
          [Unit]
          Description=NVIDIA Persistence Daemon
          After=multi-user.target

          [Service]
          Type=forking
          ExecStart=/usr/bin/nvidia-persistenced --verbose
          ExecStop=/usr/bin/killall nvidia-persistenced
          Restart=always

          [Install]
          WantedBy=multi-user.target
        path: /etc/systemd/system/nvidia-persistenced.service

      # NVIDIA Powerd
      - content: |
          [Unit]
          Description=NVIDIA Power Management

          [Service]
          ExecStart=/usr/bin/nvidia-powerd
          Restart=always

          [Install]
          WantedBy=graphical.target
        path: /etc/systemd/system/nvidia-powerd.service

      # Hyprland + NVIDIA Environment
      - content: |
          env = LIBVA_DRIVER_NAME,nvidia
          env = __GLX_VENDOR_LIBRARY_NAME,nvidia
          env = GBM_BACKEND,nvidia-drm
          env = __GL_GSYNC_ALLOWED,1
          env = __GL_VRR_ALLOWED,1
          env = __GL_MaxFramesAllowed,1
        path: /etc/environment

      # Coolbits for fan & OC
      - content: |
          Section "Device"
              Identifier "Nvidia Card"
              Driver "nvidia"
              Option "Coolbits" "28"
              Option "AllowEmptyInitialConfiguration"
          EndSection
        path: /etc/X11/xorg.conf.d/90-nvidia-coolbits.conf

      # LACT Daemon
      - content: |
          [Unit]
          Description=LACT GPU Control
          After=graphical.target

          [Service]
          ExecStart=/usr/bin/lactd
          Restart=always

          [Install]
          WantedBy=graphical.target
        path: /etc/systemd/system/lactd.service

      # LACT Fan Curve
      - content: |
          {
            "version": 1,
            "fan_control": {
              "enabled": true,
              "default_mode": "curve",
              "curve": [
                {"temp": 30, "speed": 25},
                {"temp": 40, "speed": 35},
                {"temp": 50, "speed": 45},
                {"temp": 60, "speed": 60},
                {"temp": 70, "speed": 75},
                {"temp": 80, "speed": 90}
              ]
            }
          }
        path: /etc/lact/config.json

      # LACT OC Profiles
      - content: |
          [profile.default]
          core_offset = 0
          mem_offset = 0
          power_limit = "default"

          [profile.oc_safe]
          core_offset = 100
          mem_offset = 300
          power_limit = "max"

          [profile.oc_aggressive]
          core_offset = 160
          mem_offset = 600
          power_limit = "max"
        path: /etc/lact/profiles.toml

      # LACT Desktop Entry
      - content: |
          [Desktop Entry]
          Type=Application
          Name=LACT GPU Control
          Exec=lact-gui
          Icon=lact
          Categories=System;Settings;
          Terminal=false
        path: /usr/share/applications/lact.desktop

  ##########################################################
  # DNF — SYSTEM, GPU, AI, GAMING, HEROIC, LACT
  ##########################################################
  - type: dnf
    repos:
      copr:
        - atim/starship
        - jakoolits/Hyprland
        - cheat/heroic-games-launcher
        - xnorbr/lact

    install:
      packages:
        # System utilities
        - micro
        - starship
        - git
        - curl
        - aria2
        - tar
        - ffmpeg

        # dev tools
        - gcc
        - gcc-c++
        - clang
        - llvm
        - cmake
        - ninja-build
        - make

        # python build stack
        - python3
        - python3-pip
        - python3-virtualenv
        - python3-devel
        - python3-wheel
        - python3-setuptools
        - python3-build

        # Wine stack
        - wine
        - wine-mono
        - wine-gecko

        # hyprland stack
        - hyprland
        - xdg-desktop-portal-hyprland
        - hyprpaper
        - waybar
        - rofi-wayland
        - grim
        - slurp
        - swaylock

        # fuse3
        - fuse3
        - fuse3-libs

        # mesa
        - mesa-libEGL
        - mesa-libGL
        - mesa-libGLU
        - libglvnd

        # CUDA + AI stack
        - cuda
        - cuda-cudart
        - cuda-nvml-devel
        - cuda-nvrtc
        - cuda-nvtx
        - libcublas
        - libcublas-devel
        - cudnn8
        - cudnn8-devel

        # gaming optimizations
        - gamemode
        - gamemode-devel
        - mango
        - mangohud
        - mangohud-core
        - vkBasalt
        - vulkan-loader
        - vulkan-tools
        - vulkan-headers
        - vulkan-validation-layers

        # Heroic native
        - heroic-games-launcher-bin

        # LACT native
        - lact

    remove:
      packages:
        - firefox
        - firefox-langpacks

  ##########################################################
  # FLATPAKS
  ##########################################################
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
      - scope: user

  ##########################################################
  # SCRIPT MODULES — AI TOOL INSTALLERS
  ##########################################################

  - type: script
    name: Install Fooocus
    run: |
      set -euo pipefail
      install -d /opt/fooocus
      if [ ! -d /opt/fooocus/.git ]; then
        git clone --depth=1 https://github.com/lllyasviel/Fooocus.git /opt/fooocus
      else
        git -C /opt/fooocus fetch --depth=1 origin
        git -C /opt/fooocus reset --hard origin/master
      fi
      if [ ! -d /opt/fooocus/.venv ]; then
        python3 -m venv /opt/fooocus/.venv
      fi
      /opt/fooocus/.venv/bin/python -m pip install --upgrade pip setuptools wheel
      /opt/fooocus/.venv/bin/python -m pip install -r /opt/fooocus/requirements_versions.txt

  - type: script
    name: Install ComfyUI
    run: |
      set -euo pipefail
      install -d /opt/comfyui
      if [ ! -d /opt/comfyui/.git ]; then
        git clone --depth=1 https://github.com/comfyanonymous/ComfyUI.git /opt/comfyui
      else
        git -C /opt/comfyui fetch --depth=1 origin
        git -C /opt/comfyui reset --hard origin/master
      fi
      if [ ! -d /opt/comfyui/.venv ]; then
        python3 -m venv /opt/comfyui/.venv
      fi
      /opt/comfyui/.venv/bin/python -m pip install --upgrade pip setuptools wheel
      /opt/comfyui/.venv/bin/python -m pip install -r /opt/comfyui/requirements.txt

  - type: script
    name: Install LM Studio
    run: |
      set -euo pipefail
      install -d /opt/lmstudio
      curl -fL "https://releases.lmstudio.ai/linux/x64/latest" -o /opt/lmstudio/LMStudio.AppImage
      if [ ! -s /opt/lmstudio/LMStudio.AppImage ]; then
        echo "LM Studio download failed" >&2
        exit 1
      fi
      chmod +x /opt/lmstudio/LMStudio.AppImage

  ##########################################################
  # SIGNING MODULE
  ##########################################################
  - type: signing
