# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json

name: scentia-os
description: Hyprland + CUDA/cuDNN + gaming + dev tools
base-image: ghcr.io/ublue-os/bazzite-nvidia
image-version: latest

modules:
  # Copy config files and scripts into the image
  - type: files
    files:
      - source: lactd.service
        destination: /etc/systemd/system/lactd.service
        mode: "0644"
      - source: environment
        destination: /etc/environment
        mode: "0644"
      - source: build-hyprland.sh
        destination: /usr/local/bin/build-hyprland.sh
        mode: "0755"

  # Layer packages via rpm-ostree (official bluebuild module)
  - type: rpm-ostree
    repos:
      - https://developer.download.nvidia.com/compute/cuda/repos/fedora39/x86_64/cuda-fedora39.repo
    install:
      - git
      - curl
      - gcc
      - gcc-c++
      - clang
      - llvm
      - make
      - cmake
      - ninja-build
      - meson
      - pkg-config
      - python3
      - python3-pip
      - python3-mako
      - wlroots-devel
      - wayland-devel
      - wayland-protocols-devel
      - libxkbcommon-devel
      - libinput-devel
      - libseat-devel
      - libevdev-devel
      - libudev-devel
      - libdrm-devel
      - libxkbcommon-x11-devel
      - waybar
      - rofi-wayland
      - grim
      - slurp
      - swaylock
      - gamemode
      - mangohud
      - vulkan-tools
      - vulkan-validation-layers
      - cuda-toolkit-12-4
      - cuda-libraries-12-4
      - cuda-libraries-devel-12-4
      - cuda-nvml-devel-12-4
      - cuda-nvrtc-12-4
      - cuda-cudart-devel-12-4

  # Build Hyprland from source after dependencies are present
  - type: script
    scripts:
      - run-build-hyprland.sh

  # Install Flatpaks using the default bluebuild module shape
  - type: default-flatpaks
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe

  # - type: signing
